In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4])

In [3]:
print(a1)

[1 2 3 4]


In [4]:
a2=np.array([[1,2,3],
             [4,5,6]])

In [5]:
print(a2)

[[1 2 3]
 [4 5 6]]


In [6]:
#type of array

In [7]:
print(a2.dtype)

int64


In [8]:
#Arange

In [9]:
a2=np.arange(2,8)
print(a2)

[2 3 4 5 6 7]


In [10]:
#reshape

In [11]:
a2.reshape(2,3)

array([[2, 3, 4],
       [5, 6, 7]])

In [12]:
#ALL ONES AND ZEROS random and linspace

In [15]:
np.zeros(2, dtype=int)

array([0, 0])

In [16]:
np.ones(12,dtype=int).reshape(3,4)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
np.ones((3,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.random.random((3,4))

array([[0.18247044, 0.80950012, 0.31744124, 0.33820805],
       [0.14483277, 0.03982859, 0.7525055 , 0.30035703],
       [0.98041774, 0.20330536, 0.33206651, 0.9102251 ]])

In [20]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
#identity

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
  #Array Attributes

In [27]:
x=np.arange(12).reshape(3,4)

In [29]:
x.shape

(3, 4)

In [30]:
x.ndim

2

In [31]:
x.size

12

In [32]:
x.dtype

dtype('int64')

In [ ]:
#chaNGING dtype

In [33]:
x.astype(float)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
#operations

In [34]:
a2+3

array([ 5,  6,  7,  8,  9, 10])

In [35]:
x*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [36]:
x**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [37]:
#logical

In [39]:
x>2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
#vector

In [42]:
x3=x

In [46]:
y=x*x3
print(y)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [48]:
#Array functions
#these are actually np build in functions

In [49]:
a1=np.random.random((3,4))
print(a1)

[[0.44360383 0.06403316 0.51282385 0.72581886]
 [0.84121766 0.62195674 0.3629753  0.9534511 ]
 [0.24764523 0.34362768 0.69950567 0.40602049]]


In [51]:
a1=a1*100
print(a1)

[[4436.03829769  640.33155719 5128.238472   7258.18864931]
 [8412.17660497 6219.56743067 3629.75301257 9534.51102508]
 [2476.45227949 3436.27683784 6995.05666164 4060.20485001]]


In [52]:
np.round(a1)

array([[4436.,  640., 5128., 7258.],
       [8412., 6220., 3630., 9535.],
       [2476., 3436., 6995., 4060.]])

In [53]:
np.floor(a1)

array([[4436.,  640., 5128., 7258.],
       [8412., 6219., 3629., 9534.],
       [2476., 3436., 6995., 4060.]])

In [54]:
np.ceil(a1)

array([[4437.,  641., 5129., 7259.],
       [8413., 6220., 3630., 9535.],
       [2477., 3437., 6996., 4061.]])

In [58]:
#statistical

In [56]:
#mean
np.mean(a1,axis=0)

array([5108.22239405, 3432.05860856, 5251.01604874, 6950.9681748 ])

In [57]:
np.mean(a1,axis=1)

array([4365.69924405, 6949.00201832, 4241.99765724])

In [59]:
#median

In [60]:
np.median(a1)

np.float64(4782.138384843325)

In [61]:
np.median(a1,axis=0)

array([4436.03829769, 3436.27683784, 5128.238472  , 7258.18864931])

In [62]:
#sum as well as similar prod max min

In [63]:
np.sum(a1)

np.float64(62226.79567844194)

In [64]:
#dot prodcut

In [66]:
a2=np.arange(12).reshape(4,3)

In [67]:
np.dot(a1,a2)

array([[ 98014.12334736, 115476.92032354, 132939.71729972],
       [126247.81959311, 154043.8276664 , 181839.83573968],
       [ 88821.01413344, 105789.00476242, 122756.99539139]])

In [68]:
#indexing and slicing

In [69]:
a1

array([[4436.03829769,  640.33155719, 5128.238472  , 7258.18864931],
       [8412.17660497, 6219.56743067, 3629.75301257, 9534.51102508],
       [2476.45227949, 3436.27683784, 6995.05666164, 4060.20485001]])

In [70]:
for i in a1:
    print(i)

[4436.03829769  640.33155719 5128.238472   7258.18864931]
[8412.17660497 6219.56743067 3629.75301257 9534.51102508]
[2476.45227949 3436.27683784 6995.05666164 4060.20485001]


In [71]:
a1[1][2]

np.float64(3629.753012572482)

In [75]:
y=np.arange(27).reshape(3,3,3)
print(y)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [73]:
#accessg 22

In [76]:
y[2,1,1]

np.int64(22)

In [77]:
#slicing

In [78]:
#accesing 0 2 6 8 18 20 24 26

In [79]:
y[::2,::2,::2]

array([[[ 0,  2],
        [ 6,  8]],

       [[18, 20],
        [24, 26]]])

In [80]:
#iterating
for i in np.nditer(y):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [82]:
for i in y:
  print(i)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [84]:
#reshaping

In [85]:
np.transpose(y)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [86]:
np.ravel(y)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [87]:
#stacking

In [88]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [92]:
x=a2+2

In [94]:
np.hstack((x,a2))

array([[ 2,  3,  4,  0,  1,  2],
       [ 5,  6,  7,  3,  4,  5],
       [ 8,  9, 10,  6,  7,  8],
       [11, 12, 13,  9, 10, 11]])

In [95]:
np.vstack((a2,x))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [96]:
#slicing

In [98]:
np.hsplit(a2,(2,2,2))

[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10]]),
 array([], shape=(4, 0), dtype=int64),
 array([], shape=(4, 0), dtype=int64),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]